# Example: Limiting concurrent executions to avoid race conditions
when:
  event: push

concurrency:
  limit: 1                    # Only 1 instance of this workflow can run at a time

steps:  
  api_build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: dev-registry.pulse-flow.app/pulse-api
      registry: dev-registry.pulse-flow.app
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      context: pulse.api
      dockerfile: pulse.api/Dockerfile
      tags:
        - latest
    # client_build:
    #   image: woodpeckerci/plugin-docker-buildx
    #   settings:
    #     repo: dev-registry.pulse-flow.app/pulse-client
    #     registry: dev-registry.pulse-flow.app
    #     username:
    #       from_secret: registry_username
    #     password:
    #       from_secret: registry_password
    #     context: pulse.client
    #     dockerfile: pulse.client/Dockerfile
    #     tags:
    #       - latest