export const ActivityTypes = {
    Strength: "strengthTraining",
    Walking: "walking",
    Hiking: "hiking",
    
    // Old below
    Cardio: "Cardio",
    HIIT: "HIIT",
    Sports: "Sports",
    FlexibilityMobility: "Flexibility/Mobility",
} as const;

export type ActivityType =
    typeof ActivityTypes[keyof typeof ActivityTypes];

export interface ActivityLogData {
    title: string;
    type: ActivityType;
    duration: number;
    notes: string;
    source: string;
}

// export type WorkoutType =
//   // Common types (supported on both platforms)
//   | 'americanFootball'
//   | 'australianFootball'
//   | 'badminton'
//   | 'baseball'
//   | 'basketball'
//   | 'bowling'
//   | 'boxing'
//   | 'climbing'
//   | 'cricket'
//   | 'crossTraining'
//   | 'curling'
//   | 'cycling'
//   | 'dance'
//   | 'elliptical'
//   | 'fencing'
//   | 'functionalStrengthTraining'
//   | 'golf'
//   | 'gymnastics'
//   | 'handball'
//   | 'hiking'
//   | 'hockey'
//   | 'jumpRope'
//   | 'kickboxing'
//   | 'lacrosse'
//   | 'martialArts'
//   | 'pilates'
//   | 'racquetball'
//   | 'rowing'
//   | 'rugby'
//   | 'running'
//   | 'sailing'
//   | 'skatingSports'
//   | 'skiing'
//   | 'snowboarding'
//   | 'soccer'
//   | 'softball'
//   | 'squash'
//   | 'stairClimbing'
//   | 'strengthTraining'
//   | 'surfing'
//   | 'swimming'
//   | 'swimmingPool'
//   | 'swimmingOpenWater'
//   | 'tableTennis'
//   | 'tennis'
//   | 'trackAndField'
//   | 'traditionalStrengthTraining'
//   | 'volleyball'
//   | 'walking'
//   | 'waterFitness'
//   | 'waterPolo'
//   | 'waterSports'
//   | 'weightlifting'
//   | 'wheelchair'
//   | 'yoga'
//   // iOS specific types
//   | 'archery'
//   | 'barre'
//   | 'cooldown'
//   | 'coreTraining'
//   | 'crossCountrySkiing'
//   | 'discSports'
//   | 'downhillSkiing'
//   | 'equestrianSports'
//   | 'fishing'
//   | 'fitnessGaming'
//   | 'flexibility'
//   | 'handCycling'
//   | 'highIntensityIntervalTraining'
//   | 'hunting'
//   | 'mindAndBody'
//   | 'mixedCardio'
//   | 'paddleSports'
//   | 'pickleball'
//   | 'play'
//   | 'preparationAndRecovery'
//   | 'snowSports'
//   | 'stairs'
//   | 'stepTraining'
//   | 'surfingSports'
//   | 'taiChi'
//   | 'transition'
//   | 'underwaterDiving'
//   | 'wheelchairRunPace'
//   | 'wheelchairWalkPace'
//   | 'wrestling'
//   | 'cardioDance'
//   | 'socialDance'
//   // Android specific types
//   | 'backExtension'
//   | 'barbellShoulderPress'
//   | 'benchPress'
//   | 'benchSitUp'
//   | 'bikingStationary'
//   | 'bootCamp'
//   | 'burpee'
//   | 'calisthenics'
//   | 'crunch'
//   | 'dancing'
//   | 'deadlift'
//   | 'dumbbellCurlLeftArm'
//   | 'dumbbellCurlRightArm'
//   | 'dumbbellFrontRaise'
//   | 'dumbbellLateralRaise'
//   | 'dumbbellTricepsExtensionLeftArm'
//   | 'dumbbellTricepsExtensionRightArm'
//   | 'dumbbellTricepsExtensionTwoArm'
//   | 'exerciseClass'
//   | 'forwardTwist'
//   | 'frisbeedisc'
//   | 'guidedBreathing'
//   | 'iceHockey'
//   | 'iceSkating'
//   | 'jumpingJack'
//   | 'latPullDown'
//   | 'lunge'
//   | 'meditation'
//   | 'paddling'
//   | 'paraGliding'
//   | 'plank'
//   | 'rockClimbing'
//   | 'rollerHockey'
//   | 'rowingMachine'
//   | 'runningTreadmill'
//   | 'scubaDiving'
//   | 'skating'
//   | 'snowshoeing'
//   | 'stairClimbingMachine'
//   | 'stretching'
//   | 'upperTwist'
//   | 'other';